---
title: "Final Project Code"
author: "Ben Giles"
date: "12/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(dplyr)
library(tidyverse)
```
```{r}
ThreeyearStats <- read.csv("threeyrnbastats.csv",
           header = TRUE,
           sep = ",",
           stringsAsFactors = FALSE)
ThreeyearStats
```

```{r}
url1 <- "https://www.basketball-reference.com/pi/shareit/vYOnK"

NBAraw1 <- url1 %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
str(NBAraw1)

url2 <- "https://www.basketball-reference.com/pi/shareit/pJVmT"

NBAraw2 <- url2 %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
str(NBAraw2)

```
```{r}
NBAdf1 <- NBAraw1[[1]]
is.data.frame(NBAdf1)

NBAdf1join <-
  NBAdf1 %>%
  filter(Rk != "Rk")

NBAdf2 <- 
  NBAraw2[[1]]
NBAdf2
colnames(NBAdf2)[3] <- "TS"
colnames(NBAdf1)[10] <- "FGpct"
colnames(NBAdf1)[12] <- "ThreePtAtt"
colnames(NBAdf1)[13] <- "ThreePtpct"
colnames(NBAdf1)[15] <- "TwoPA"
colnames(NBAdf1)[16] <- "TwoPpct"
colnames(NBAdf1)[17] <- "eFGpct"
NBAdf1join <-
  NBAdf1 %>%
  filter(Rk != "Rk")

is.data.frame(NBAdf2)

#Jointbl <- NBAdf2[ -c(1,3:8,10:29) ]
NBAFullStatNoFilter <-
  NBAdf1 %>%
    mutate(G = as.numeric(G),
         FG = as.numeric(FG),
         eFGpct = as.numeric(eFGpct),
         PTS = as.numeric(PTS),
         AST = as.numeric(AST),
         TRB = as.numeric(TRB),
         BLK = as.numeric(BLK),
         ThreePtpct = as.numeric(ThreePtpct),
         TwoPpct = as.numeric(TwoPpct),
         TwoPA = as.numeric(TwoPA))
NBAFullstat <-

  inner_join(NBAdf1join,NBAdf2,by="Player") %>%
  
  mutate(G = as.numeric(G),
         FG = as.numeric(FG),
         eFGpct = as.numeric(eFGpct),
         PTS = as.numeric(PTS),
         AST = as.numeric(AST),
         TRB = as.numeric(TRB),
         BLK = as.numeric(BLK),
         ThreePtpct = as.numeric(ThreePtpct),
         TwoPpct = as.numeric(TwoPpct),
         TwoPA = as.numeric(TwoPA),
         TS = as.numeric(TS)
         
         ) %>%
  
  filter(!grepl("-", Pos)) %>% #took out the 5 players who are listed at 2 positions becuase they would 
  filter(G >= 51) 

NBAFullstat
RelevantStats <-
  NBAFullstat %>%
  select(Pos, PTS, AST, TRB, BLK, ThreePtpct, TwoPpct)
RelevantStats <- tibble::rowid_to_column(RelevantStats, "ID")
RelevantStats

#NBABasketballPerGame <- 
  #cbind(NBAbballraw[[1]], NBAbballraw[[2]]) %>%
  #(Name != "Total")
#NBABasketballPerGame


```

```{r}
Positionpts <-
  NBAFullstat %>%
  group_by(Pos) %>%
  
  spread(key = Pos, value =PTS) %>%
  select(C, PF, PG, SF, SG)

Positionpts %>%
  ggplot(aes(x = Pos,na.rm = TRUE)) +
  geom_density()
Positionpts %>%
  filter_all(all_vars(. > 1))

Positionpts
Positionast <-
  NBAFullstat %>%
  group_by(Pos) %>%
  summarise(avgAST = mean(AST)) %>%
  spread(key = Pos, value = avgAST, fill = 0)

PositionTRB <-
  NBAFullstat %>%
  group_by(Pos) %>%
  summarise(avgTRB = mean(TRB)) %>%
  spread(key = Pos, value = avgTRB, fill = 0)
PositionTRB
PositionBLK <-
  NBAFullstat %>%
  group_by(Pos) %>%
  summarise(avgBLK = mean(BLK)) %>%
  spread(key = Pos, value = avgBLK, fill = 0)
Position3Ppct <-
  NBAFullstat %>%
  group_by(Pos) %>%
  summarise(avgThreePpct = mean(ThreePtpct)) %>%
  arrange(desc(avgThreePpct))
PositionTwoPpct <-
  NBAFullstat %>%
  group_by(Pos) %>%
  summarise(avgTwoPpct = mean(TwoPpct)) %>%
  spread(key = Pos, value = avgTwoPpct, fill = 0)

PositionWideTable <-
  Positionpts %>%
  #left_join(Positionpts, Positionast, by) %>%
  #left_join(., PositionTRB) %>%
  #left_join(., PositionBLK) %>%
  #left_join(., Position3Ppct) %>%
  #left_join(., PositionTwoPpct)
PositionWideTable

NBAFullstat %>%
  ggplot(aes(x=eFGpct, y=ThreePtpct)) +
  geom_line(size=2, aes(color=Pos)) +
  facet_wrap(~ Pos) +
  theme_bw() #theme_gray, theme_linedraw, theme_classic, and so on. 
```
```{r}
NBAFullstat %>%
  ggplot(aes(x=ThreePtAtt, y=TS)) +
  geom_line(size=2, aes(color=Pos)) +
  facet_wrap(~ Pos) +
  geom_smooth() +
  theme_bw() #theme_gray, theme_linedraw, theme_classic, and so on. 
```
```{r}
PositionTable %>%
  ggplot(aes(x = Pos, y = TRB)) +
  geom_bar(stat = "identity")

NBAFullstat %>%
  ggplot(aes( x = TwoPpct)) +
  geom_histogram() +
  facet_wrap( ~ Pos)
NBAFullstat %>%
  ggplot(aes( x = ThreePtpct)) +
  geom_histogram() +
  facet_wrap( ~ Pos)

```

```{r}
#function for median data in league
TEAMstatstbl <-
  NBAFullStatNoFilter%>%
  group_by(Tm) %>%
  filter(Tm != "TOT") %>%
  filter(Tm != "Tm") %>%
  summarise(total = sum(PTS)) %>%
  spread(key = Tm, value = total, fill = 0)
TEAMstatstbl
PositionWidetbl <-
  NBAFullstat%>%
  group_by(Pos) %>%
  summarise(total = mean(PTS)) %>%
  spread(key = Pos, value = total, fill = 0, convert = TRUE)
PositionWidetbl

PositionTable <-
  RelevantStats%>%
  group_by(Pos) %>%
  summarise_at(c(2:6), mean, na.rm = TRUE) %>%
  arrange(desc(PTS))
PositionTable
PositionTable %>%
  ggplot(aes(x = Pos, y = PTS)) +
  geom_bar(stat = "identity")

NBAFullstat %>% 
  select(Player, Pos, AST) %>%
  filter(rank(desc(AST)) <= 11)  %>%
  arrange(desc(AST))
NBAFullstat %>%
  select(Player, Pos, TRB) %>%
  filter(rank(desc(TRB)) <= 11) 

NBAFullstat %>%
  ggplot(aes(y = AST, x = Pos)) + 
  geom_boxplot(aes(color = Pos, fill = Pos), 
               alpha = 0.25, outlier.size = 2, outlier.colour = "gray") + 
  xlab("Position") + 
  ylab("Assists Per Game") + 
  theme(legend.position = "top") +  
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
NBAFullstat %>%
  ggplot(aes( y = TS , x = PTS)) +
  stat_smooth()
```
